### ISSUE TITLE
'Email Copied' confirmation bubble/popup text has no contrast in dark mode.

### ISSUE THREAD

**Issue by 3obby** [RubricLab/rubric#8]
In dark mode, it's white text on white background.

![image](https://github.com/RubricLab/rubric/assets/96895030/de26fa85-ad58-4de6-b0ff-bab250bfd519)

**Comment by DexterStorey** [comment]
Will fix! Thanks @3obby 🙌

**Comment by tedspare** [comment]
Fixed by Dexter or Sarim, thanks @3obby! 

![image](https://github.com/RubricLab/rubric/assets/36117635/3fd9cfc7-e1c4-420c-83a9-587011fc3c99)
